### ISSUE TITLE
Support Azure Speech Service

### ISSUE THREAD

**Issue by vijjo** [Language-Tools/anki-hyper-tts#100]
Currently, you're implementing **Azure Cognitive Service,** not **Azure Speech Service**. The Cognitive Service only has standard-tier price, not free-tier one while the Speech Service has free-tier price. For Text-to-Speech function, the Speech service offers 500K characters free per month.

<img width="600" alt="image" src="https://user-images.githubusercontent.com/31264468/232383763-25614f4b-1be3-44b3-b1d8-b309dceec29f.png">

Can you please support Azure Speech Service, please!

**Comment by luc-languagetools** [comment]
What happens when you try to use your speech service key in HyperTTS?

**Comment by luc-languagetools** [comment]
Could it be that there's a bit of lag after you and the service on azure portal, and the moment it starts working ? I remember experiencing such transient issues.

**Comment by vijjo** [comment]
It might be, I'm not sure. It works well now.
