### ISSUE TITLE
Adding HyperTTS audio causing Anki to crash

### ISSUE THREAD

**Issue by tyschauster** [Language-Tools/anki-hyper-tts#101]
Not sure if this is happening to everybody but yesterday, all of the sudden, when I add audio even for a single card via HyperTTS (any service), it causes my Mac's "spinning wheel of death" to appear.  Takes a good minute for it to go away.  And most of the time I just have to "Force Quit".  So it has rendered HyperTTS useless.  AwesomeTTS seems to be working just fine, but it isn't so...awesome imo, once you've used HyperTTS.  Is this ubiquitous or just me?

**Comment by luc-languagetools** [comment]
Hi, I was curious whether you're still experiencing this issue ? I put in a fix for an issue which may be related, around a month ago.

**Comment by tyschauster** [comment]
I haven’t been adding a lot of audio lately but the last time I added some a few weeks ago it was working just fine. I really don’t think it has happened again since that last time. But I’ll be adding a lot more audio once I’m done creating a deck I’m working on in a few days. And if it happens I’ll let you know. But so far so good. -TySent from my iPhoneOn Jul 28, 2023, at 10:18 PM, Luc ***@***.***> wrote:﻿
Hi, I was curious whether you're still experiencing this issue ? I put in a fix for an issue which may be related, around a month ago.

**Comment by luc-languagetools** [comment]
Definitely please let me know if it happens again.

**Comment by tyschauster** [comment]
Hi Luc,

Hey quick question.  My renewal date for credits is supposed to be today but I’m still not seeing them.  I just ran out of old credits.  If I renew them, will it then also renew me again later in the day and charge me again? Or how would that work?  I just $10 worth and I’m trying to get them now so I can keep going on my project.

Thanks,
-Ty

p.s. - Everything is working fine though.  I just ran about a thousand cards. No issues.  Oh, and thanks for the heads up on the ElevenLabs credits.

**Comment by tyschauster** [comment]
Actually, looks like the 11th is my next invoice date.  So I guess my question is, can I click the green “Update Subscription” button now and get $10 or do I have to wait til the 11th?

-Ty

**Comment by luc-languagetools** [comment]
looks like you upgraded, everything OK now ?

**Comment by tyschauster** [comment]
Ya all good.  It just wouldn’t let me do just $10, but no matter. I’m sure I’ll eventually use the credits anyways.    Thanks!

**Comment by luc-languagetools** [comment]
the billing system is not super flexible, I'm trying to think of ways to improve this.

**Comment by tyschauster** [comment]
Ya, I’m actually trying to cancel/postpone since I have plenty of credits for the time being and I cannot find where to do it.  I thought I had an email with a “Cancel Subscription” link but I must have lost it.  And there is nowhere on your site that I can find to go to do that.  Probably should be more prominent.  Would you be able to cancel my subscription for now?  Or can you direct me to where to go to do so?

Thanks,
-Ty
