### ISSUE TITLE
Unable to set speech speed for real time native windows TTS

### ISSUE THREAD

**Issue by coworo** [Language-Tools/anki-hyper-tts#103]

**Comment by luc-languagetools** [comment]
Which voice are you using?

**Comment by coworo** [comment]
> Which voice are you using?

Microsoft Zira

**Comment by luc-languagetools** [comment]
Hi, I added this feature a few weeks ago. If you left a review regarding this feature on ankiweb here https://ankiweb.net/shared/info/111623432 , please update your review.
