### ISSUE TITLE
icons in edit mode have disappeared

### ISSUE THREAD

**Issue by PawelBanasiewicz** [Language-Tools/anki-hyper-tts#107]
![screenshot_02](https://github.com/Language-Tools/anki-hyper-tts/assets/44553788/61abbdee-b20a-4bb6-a6c2-9d410f609761)

**Comment by Derek-Chu** [comment]
Facing similar issue, none of the icons show up for me:
![image](https://github.com/Language-Tools/anki-hyper-tts/assets/23140681/72aef3a4-9501-4a52-af27-67ade5ec157b)

**Comment by luc-languagetools** [comment]
Many apologies, this is a bug I introduced in 0.74, fixed in 0.75.

**Comment by Derek-Chu** [comment]
Looks good to me :)
![image](https://github.com/Language-Tools/anki-hyper-tts/assets/23140681/ef67310e-99ac-41b6-af7e-afceda181725)

**Comment by PawelBanasiewicz** [comment]
thanks for prompt reaction 
works perfectly
