### ISSUE TITLE
Encountered an error while Adding Audio to Note

### ISSUE THREAD

**Issue by Ziyao3000** [Language-Tools/anki-hyper-tts#108]
Hi there!

I was trying to add voice as usual to my card today but encountered this: "Encountered an error while Adding Audio to Note: Could not request audio for [congruent]: Status code: 429 (b'{"'error": "Maxed out trial quota. Please sign up for the paid plan."}n') (voice: English (US), Any, None, Forvo)"
Could you help me with that?

Thank you!

**Comment by luc-languagetools** [comment]
Hi, you've used up your free trial quota, you can purchase a paid plan on https://languagetools.anki.study/hypertts-pro
or you can keep using the free services.
