### ISSUE TITLE
Adding ElevenLabs API key causes crash when starting HyperTTS

### ISSUE THREAD

**Issue by Amosnomor** [Language-Tools/anki-hyper-tts#122]
Encountered an unknown error while Launching HyperTTS Batch Dialog from Browser: 'zh'

ElevenLabs sent me an email today about a new lanaguage model, and supporting Chinese.  I started up Anki on Linux, and added my ElevenLabs free account API key in the HyperTTS add-on service configuration, and then ran into this error when trying to use HyperTTS.   Dis-enabling the ElevenLabs Custom restores proper functioning.
    
    Anki 2.1.62 (77dd1dc1) Python 3.9.15 Qt 5.15.2 PyQt 5.15.5
    Platform: Linux-5.15.0-79-generic-x86_64-with-glibc2.31
    Flags: frz=True ao=True sv=2
    Add-ons, last update check: 2023-08-23 14:08:31
    
    
    ===Add-ons (active)===
    (add-on provided name [Add-on folder, installed at, version, is config changed])
    '' ['myaddon', 0, 'None', '']
    Advanced Browser ['874215009', 2023-07-01T12:55, 'None', '']
    HyperTTS - Add speech to your flashcards ['111623432', 2023-08-15T16:35, 'None', mod]
    Set Font Size ['651521808', 2022-05-01T11:02, 'None', mod]
    
    ===IDs of active AnkiWeb add-ons===
    111623432 651521808 874215009
    
    ===Add-ons (inactive)===
    (add-on provided name [Add-on folder, installed at, version, is config changed])
    Change Interface Font ['1431333984', 2023-07-20T23:17, 'None', mod]

**Comment by luc-languagetools** [comment]
Thanks for the report, I will aim to fix this within 24hrs

**Comment by luc-languagetools** [comment]
Please update to HyperTTS 0.88, ElevenLabsCustom should work after that.

**Comment by Amosnomor** [comment]
It is working now.  Thank you.
