### ISSUE TITLE
No toolbar in editor Anki 2.1.66

### ISSUE THREAD

**Issue by darren-moore** [Language-Tools/anki-hyper-tts#125]
I'm on Anki 2.1.66 and addon version .88
The toolbar in the editor does not appear and I see the following errors with the web view inspector.

![image](https://github.com/Language-Tools/anki-hyper-tts/assets/16497418/843d52d7-a3d4-41a1-8079-29b383570fe7)
[log.txt](https://github.com/Language-Tools/anki-hyper-tts/files/12449994/log.txt)

**Comment by luc-languagetools** [comment]
Thank you, I'll try to fix this as soon as possible

**Comment by luc-languagetools** [comment]
at first sight i'm not completely sure which change in Anki 2.1.66 might have caused this. I posted a message in this thread: https://forums.ankiweb.net/t/anki-2-1-66-beta/32463/25
if you need this to work immediately, I suggest downgrading to 2.1.65, and i'll keep looking for a way to fix this on 2.1.66.

**Comment by Amosnomor** [comment]
Another data point here... I am seeing the same symptom (no HyperTTS toolbar browser card editor) on Anki 2.1.62 / Qt 5.  It showed up in one of the past two or three HyperTTS updates.

    
    Anki 2.1.62 (77dd1dc1) Python 3.9.15 Qt 5.15.2 PyQt 5.15.5
    Platform: Linux-5.15.0-79-generic-x86_64-with-glibc2.31
    Flags: frz=True ao=True sv=2
    Add-ons, last update check: 2023-08-29 10:34:34
    
    
    ===Add-ons (active)===
    (add-on provided name [Add-on folder, installed at, version, is config changed])
    '' ['myaddon', 0, 'None', '']
    Advanced Browser ['874215009', 2023-07-01T12:55, 'None', '']
    HyperTTS - Add speech to your flashcards ['111623432', 2023-08-30T06:56, 'None', mod]
    Set Font Size ['651521808', 2022-05-01T11:02, 'None', mod]
    
    ===IDs of active AnkiWeb add-ons===
    111623432 651521808 874215009
    
    ===Add-ons (inactive)===
    (add-on provided name [Add-on folder, installed at, version, is config changed])
    Change Interface Font ['1431333984', 2023-07-20T23:17, 'None', mod]

**Comment by Amosnomor** [comment]
0.91 fixes this for me.  Thank you.

   
    Anki 2.1.62 (77dd1dc1) Python 3.9.15 Qt 5.15.2 PyQt 5.15.5
    Platform: Linux-5.15.0-79-generic-x86_64-with-glibc2.31
    Flags: frz=True ao=True sv=2
    Add-ons, last update check: 2023-08-30 22:50:43
    
    
    ===Add-ons (active)===
    (add-on provided name [Add-on folder, installed at, version, is config changed])
    '' ['myaddon', 0, 'None', '']
    Advanced Browser ['874215009', 2023-07-01T12:55, 'None', '']
    HyperTTS - Add speech to your flashcards ['111623432', 2023-08-30T21:32, 'None', mod]
    Set Font Size ['651521808', 2022-05-01T11:02, 'None', mod]
    
    ===IDs of active AnkiWeb add-ons===
    111623432 651521808 874215009
    
    ===Add-ons (inactive)===
    (add-on provided name [Add-on folder, installed at, version, is config changed])
    Change Interface Font ['1431333984', 2023-07-20T23:17, 'None', mod]

**Comment by manyet1k** [comment]
I'm using Anki 2.1.66 Flatpak version with HyperTTS 0.91, and it's still the same for me.

As a matter of fact, the toolbar didn't appear a while ago too, and then it was fixed with an update -- for some reason now it broke again, apparently.

**Comment by luc-languagetools** [comment]
the HyperTTS toolbar is not compatible with Anki 2.1.66 . And to be completely transparent, it's not clear that there is a way to fix it. The Anki addon support to add custom toolbars is not very stable, but i'm looking for a solution.

**Comment by lowkeydying** [comment]
Hi commenting bc I also had the toolbar disappearing issue and just want to be notified if it's fixed in the future for Anki 2.1.66.

**Comment by omega3** [comment]
@lowkeydying
On the right of this page you have Notifications option. Just click to subscribe.

**Comment by SebastianEShelby** [comment]
Is this causing the HyperTTS record button to be missing? Is there going to be a fix?

**Comment by jebra102** [comment]
Sadly, I don't see how that helps the issue with the lack of a button in the card editor. I hope it will come back in a later release. For now, it works, it just isn't ideal.

**Comment by jebra102** [comment]
Yeah, I think I'm just blind as a bat. I found the buttons now. But generally, a tooltip for them might be useful. But that is a different issue.
Very sorry for the confusion. It was pretty late where I was.
