### ISSUE TITLE
add belarusian support for Forvo

### ISSUE THREAD

**Issue by luc-languagetools** [Language-Tools/anki-hyper-tts#127]
requested by Aaron over email

**Comment by slapula** [comment]
Do you accept outside PRs?  I was actually able to get this working myself and can cut a PR tomorrow.

**Comment by luc-languagetools** [comment]
Yes i do however I have a script to generate the voicelist, which is the right way to do this

**Comment by slapula** [comment]
Ok! That makes sense. I did it manually and it works for the most part but the plugin throws a weird error when finishing a round of audio downloading.

**Comment by slapula** [comment]
@luc-languagetools do you mind sharing the script? I could certainly run it and test it then cut a PR

**Comment by luc-languagetools** [comment]
Belarusian support for Forvo added in HyperTTS 1.07.
