### ISSUE TITLE
Add option for rate limiting

### ISSUE THREAD

**Issue by telotortium** [Language-Tools/anki-hyper-tts#13]
I'm using the Google Cloud TTS Explorer keys, and so far it looks like it's not possible to change the rate limiting so that you can add text to more than 20 or so at a time and expect them all to have audio when the batch add process is complete. AwesomeTTS has such a feature.

**Comment by luc-languagetools** [comment]
should be possible without too much difficulty, thanks.

**Comment by luc-languagetools** [comment]
added in v0.19 for both azure and google.
