### ISSUE TITLE
Forvo HTTP 400

### ISSUE THREAD

**Issue by promisedlandt** [Language-Tools/anki-hyper-tts#130]
Hello Luc,

while using HyperTTS today, I'm getting the following error message:

> Encountered an error while Previewing Audio: Could not request audio for [쓸데없다]: Status code: 400 (b'{"error": "Unable to retrieve audio from Forvo"}\n') (voice: Korean, Any, None, Forvo)

Forvo requests used to work as recently as last week (I don't have an exact date unfortunately).

The word is [available on Forvo](https://forvo.com/word/%EC%93%B8%EB%8D%B0%EC%97%86%EB%8B%A4/#ko), and I can retrieve it with [anki-forvo-dl](https://ankiweb.net/shared/info/858591644).  
The Forvo API docs seem pretty shit, I was unable to documentation for the responses, so I have no idea what the issue could be.

**Comment by luc-languagetools** [comment]
Are you using the HyperTTS pro plan, or your own Forvo key ? On HyperTTS pro, i've been negotiating with Forvo for a new contrat with expanded capacity and it's moving along but still not active yet.

**Comment by promisedlandt** [comment]
I'm using HyperTTS pro, and I don't mind waiting for your negotiations to finish :smile: 

I reported it only because I thought it might be a technical issue.
