### ISSUE TITLE
On service error, continue with next voice

### ISSUE THREAD

**Issue by promisedlandt** [Language-Tools/anki-hyper-tts#131]
Hello Luc,

this is a follow-up of #130 (Forvo 400).

My voice setup is "Priority" with the following list:
- Forvo
- Naver (Premium)

If there is any error with Forvo, I would like HyperTTs to try the next voice, i.e. Naver.  
This works fine for 404 of course, but apparenly not for "unexpected" errors like the linked 400.

**Comment by luc-languagetools** [comment]
In theory, 400 shouldn't happen. I am planning on introducing some repeat on timeout functionality. But what you are describing should be possible, you're right that right HyperTTS only moves to the next voice if it detects "not found". And this "priority" mode is mainly designed for "dictionary" services like Forvo where a limited number of words are available.

**Comment by luc-languagetools** [comment]
are you a HyperTTS pro subscriber ? I just signed a new contract with Forvo and the reliability should improve.

**Comment by promisedlandt** [comment]
> are you a HyperTTS pro subscriber ? I just signed a new contract with Forvo and the reliability should improve.

I am a HyperTTS pro subscriber. Happy to hear about the new contract!

**Comment by luc-vocab** [comment]
just curious, has the failure rate with forvo decreased ?

**Comment by promisedlandt** [comment]
I'm sorry, due to health reasons I haven't used Anki much in the past few months. But when I used it, I had no issues with Forvo. I'll gladly close this.
