### ISSUE TITLE
Save mapping from hypertts hashes to text somewhere

### ISSUE THREAD

**Issue by ivankra** [Language-Tools/anki-hyper-tts#134]
Feature request: it would be nice if the addon would save the map from hash in filenames to source text and voice options somewhere.

Currently it seems there's no way to find what text a particular file was generated from, short of regenerating it again. The mapping is useful for various scripting workflows with anki, like bulk deleting tts files with bad options, reusing audio when generating new decks, etc.

For my purposes I've hacked get_hash_for_audio_request() in hypertts.py like below, it's enough for me, something like this would be very useful as core feature
```py
    def get_hash_for_audio_request(self, source_text, voice, options):
        ...
        with open('hypertts.tsv', 'a') as fp:
            fp.write('%s\t%s\t%s\t%s\n' % (res, source_text, str(voice.voice_key), str(options)))
        return res
```

**Comment by luc-languagetools** [comment]
same as #138  , generating parameters should be stored as metadata somewhere.
