### ISSUE TITLE
Slow down speech in a more natural sounding way

### ISSUE THREAD

**Issue by wadid** [Language-Tools/anki-hyper-tts#135]
Because the voice sounded quite fast (Azure neural, russian voice) I did set the rate to 0.7. But then it starts to sound unnatural. Do I understand it right that the rate is applied after the voice is generated and thats why it sounds distorted? Is there an option that produces speach output that is naturally slow? I hope its understandable what I mean.

**Comment by luc-languagetools** [comment]
I'm afraid I can't help here, this is 100% done on the azure side, there's nothing HyperTTS can do. You'll have to experiment with different services.

**Comment by freeyob** [comment]
> I'm afraid I can't help here, this is 100% done on the azure side, there's nothing HyperTTS can do. You'll have to experiment with different services.

Can I controll the rate of voice on learning. I find that speech of some sentence  are very fast.

**Comment by luc-languagetools** [comment]
@freeyob a lot of services allow you to configure the rate of speech, but some don't. Unfortunately HyperTTS cannot do anything if the voice doesn't sound correct, that's up to the service. Closing this issu efor now, feel free to re-open if you have more questions.
