### ISSUE TITLE
Polish vowel stress  "ę" (phoneme ɛ̃ ) ; via azure PL-pl

### ISSUE THREAD

**Issue by Gursharn007** [Language-Tools/anki-hyper-tts#136]
Hello, I'm using HyperTTS with microsoft's azure service for Polish.

when generating speech from text using azure's PL service, how can i add stress on the vowel "ę"?

for example:
the word "cukrzycę" is pronounced as "cukrzy-ce"

it pronouces "ę" as a normal "e", 
which leads to alot of confusion

I know azure supports SSML and IPA 
[](https://learn.microsoft.com/en-us/azure/ai-services/speech-service/speech-ssml-phonetic-sets#pl-pl)

the ipa symbol for "ę" is  ɛ̃ 

so what are my options?

**Comment by luc-languagetools** [comment]
This azure documentation seems to have some pointers: https://learn.microsoft.com/en-us/azure/ai-services/speech-service/speech-synthesis-markup-pronunciation
would you be able to give it a read and see whether it makes sense to you ? You'll need to add the SSML code to your field and make sure it's passed through to Azure
