### ISSUE TITLE
Error after generating sounds (anki.errors.InvalidInput: target undo op not found)

### ISSUE THREAD

**Issue by Pracium** [Language-Tools/anki-hyper-tts#141]
Hey,
since the last update I get this error every time after generating sounds.

```
Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue to the add-on author.
Debug info:
Anki 23.10.1 (fac9e0ee) Python 3.11.5 Qt 6.6.0 PyQt 6.6.0
Platform: Linux-6.6.1-arch1-1-x86_64-with-glibc2.38
Flags: frz=False ao=True sv=3
Add-ons, last update check: 2023-11-12 23:02:15
Add-ons possibly involved: ⁨HyperTTS - Add speech to your flashcards⁩

Caught exception:
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/aqt/taskman.py", line 138, in _on_closures_pending
    closure()
  File "/home/patrick/.local/share/Anki2/addons21/111623432/anki_utils.py", line 109, in undo_end_fn
    aqt.mw.col.merge_undo_entries(undo_id)
  File "/usr/lib/python3.11/site-packages/anki/collection.py", line 1027, in merge_undo_entries
    return self._backend.merge_undo_entries(target)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/anki/_backend_generated.py", line 255, in merge_undo_entries
    raw_bytes = self._run_command(3, 11, message.SerializeToString())
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/anki/_backend.py", line 158, in _run_command
    raise backend_exception_to_pylib(err)
anki.errors.InvalidInput: target undo op not found
```

**Comment by luc-languagetools** [comment]
@Pracium were you by any chance generating multiple sounds together in close succession ? I made a change in HyperTTS 1.03 to prevent generating for two presets at once.

**Comment by jbvoigt3** [comment]
yes, I was. But it really wasn't necessary. I just didn't see another option. Once you push the button, it automatically generates all of them. Even for some that are not empty.Jack"We are free to choose, but we are not free from the consequences of our choice."On Nov 15, 2023, at 10:56, Luc ***@***.***> wrote:﻿
@Pracium were you by any chance generating multiple sounds together in close succession ? I made a change in HyperTTS 1.03 to prevent generating for two presets at once.

**Comment by Pracium** [comment]
> were you by any chance generating multiple sounds together in close succession

If I add or edit a card I select all cards of that note type and click on generate on my two presets for the languages is use.

**Comment by luc-languagetools** [comment]
@Pracium would you be able to record a video ? I'm having trouble reproducing this bug.

**Comment by jbvoigt3** [comment]
Still crashing.

 Screen Recording 2023-11-16 at 5.24.21 PM.mov
<https://drive.google.com/file/d/1caDaJwWh6iWhNyeR364Nic6swCDkqPKm/view?usp=drive_web>

Respectfully,

Jack Voigt
***@***.***

"We are free to choose, but we are not free from the consequences of our
choice."

**Comment by luc-languagetools** [comment]
@jbvoigt3 please try after updating to HyperTTS 1.04, hopefully this version makes the issue go away.

**Comment by jbvoigt3** [comment]
When I started Anki, it updated HyperTTS, but I don’t know where to find the version number.
Sadly, in any case, it immediately popped up with the error screen.
See attached.

**Comment by luc-languagetools** [comment]
@jbvoigt3 did you  forget to attach the screenshot ?

**Comment by jbvoigt3** [comment]
Evidently I did.  Sorry.  It was late and I wanted to get it to you.  lol

Respectfully,

Jack Voigt
***@***.***

"We are free to choose, but we are not free from the consequences of our
choice."

**Comment by luc-languagetools** [comment]
@jbvoigt3 I still don't see the error

**Comment by jbvoigt3** [comment]
Don't know what to tell you.  I'm current with Anki and HyperTTS.  Database checks out okay.  I don't understand the text of the error message generated.  Do you not see anything in it to guide you?Tell me what you would like me to try and I'll accommodate you.  Jack(Sent from my iPad)On Nov 19, 2023, at 7:18 AM, Luc ***@***.***> wrote:﻿
@jbvoigt3 I still don't see the error

**Comment by luc-languagetools** [comment]
I have still not seen the error message that you're experiencing on HyperTTS 1.04. It could be that github is not pressing attachments over email properly. If you are unable to upload the screenshot on github, you can email me hypertts@airpost.net

**Comment by Pracium** [comment]
> @Pracium would you be able to record a video ? I'm having trouble reproducing this bug.

Hey,
I just added some new cards and generated audios for all of them (100+ cards at once). It worked without showing an error message at the end, so I think your update fixed it.
