### ISSUE TITLE
API Key expiredm despite only used 907 characters

### ISSUE THREAD

**Issue by steve-sapp** [Language-Tools/anki-hyper-tts#142]
Hi
i am probably missing something or doing something wrong. 
As far as i am aware the HyperTTS Pro Trial is supposed to be good for 5000 Characters. I have only used 907. But when i try to add an audio file i get the following message: Encountered an error while Running all rules: Could not request audio for ... Status code: 401 (b'{"error": "API Key expired"}\n')

**Comment by luc-languagetools** [comment]
Please email me hypertts@airpost.net so that we can figure this out

**Comment by luc-languagetools** [comment]
closing, let's continue discussion by email if you're still having the problem.
