### ISSUE TITLE
Naver Papago is not working

### ISSUE THREAD

**Issue by bbeito** [Language-Tools/anki-hyper-tts#148]
Just yesterday Naver Papago was working completely fine, and now when I try to make any audio (even previews) I get this error: 
![Screenshot 2023-11-27 181843](https://github.com/Language-Tools/anki-hyper-tts/assets/152230137/5d179286-fdcd-4c50-8f45-845fe1f6ac8d)

**Comment by loayyasserrr** [comment]
same here!

**Comment by luc-languagetools** [comment]
Did you update to AwesomeTTS 1.83 ?

**Comment by luc-languagetools** [comment]
Should be fixed in the latest HyperTTS

**Comment by pinetreemoonlight** [comment]
> Should be fixed in the latest HyperTTS

Is it already fixed when downloading the add-on from ankiweb or you mean n GitHub?

**Comment by salesjulia** [comment]
Same error here!

**Comment by luc-languagetools** [comment]
@pinetreemoonlight @salesjulia can you tell me which version of HyperTTS you're using ?

**Comment by salesjulia** [comment]
> @pinetreemoonlight @salesjulia can you tell me which version of HyperTTS you're using ?

I'm using the latest version of HyperTTS, but my anki was outdated. Today I updated anki to version 23.12.1 and the Papago function is working fine. Thank you!

**Comment by luc-languagetools** [comment]
OK good to know,  closing the issue for now, please re-open if you're still experiencing issues.
