### ISSUE TITLE
[Feature Request] Custom domains for Azure Speech Service 

### ISSUE THREAD

**Issue by vlev** [Language-Tools/anki-hyper-tts#159]
Hi,

First of all, thank you for the great work! 
I find this plugin to be extremely useful.

Is there a chance, you can add the support of custom domains for Azure Speech Service? 
I believe, at the moment, the target endpoint is calculated as [location].api.cognitive.microsoft.com.
Would be nice to be able to provide a custom one, e.g. custom-domain.cognitiveservices.azure.com

This is needed in order to enable ip-based firewall rules on the service.

**Comment by luc-languagetools** [comment]
just curious what is the main reason to use custom api domains ?

**Comment by vlev** [comment]
The main motivation is security considerations - I prefer to limit access to paid cloud resources to specific IPs. 
With Azure Cognitive services (including text to speach) this configuration requires custom domains.
Here is a fresh thread on this - https://learn.microsoft.com/en-us/answers/questions/1154764/how-to-enable-networking-for-azure-cognitive-servi
I've also done some experimenting and can confirm that this limitation is in place.

**Comment by luc-vocab** [comment]
I don't have time to implement this. If you want it, you can create your own custom service, it's extremely easy.
