### ISSUE TITLE
Elevenlabs and OpenAI only have English (US)

### ISSUE THREAD

**Issue by echoIIImk2** [Language-Tools/anki-hyper-tts#169]
Elevenlabs and OpenAI only have English (US) as an option, is it possible to add English (UK)?

**Comment by luc-languagetools** [comment]
This won't accomplish what you are looking for, there's no way to tell the ElevenLabs and OpenAI engines that you want a UK accent.

**Comment by luc-vocab** [comment]
closing for now, since this cannot be implemented.
