### ISSUE TITLE
Add option to not complain if source field is empty for one of the rules

### ISSUE THREAD

**Issue by raine** [Language-Tools/anki-hyper-tts#170]
Hello!

Use case: I have two fields that I generate sound for, but only the first field always has sound. The second field only sometimes had something.

Could it be possible to add option to not show the error if a field is empty?

<img width="276" alt="Screenshot 2024-03-13 at 23 05 22" src="https://github.com/Language-Tools/anki-hyper-tts/assets/11027/72e01395-e8fb-4dfc-910b-7dcc77d948a0">

**Comment by Amosnomor** [comment]
This is also requested by [ preset rules: allow skipping when source field is empty #143 ](https://github.com/Language-Tools/anki-hyper-tts/issues/143).

Making the same comment here, it would be nice if the solution also allowed for advanced templates to return an empty string a special value, without generating an error.

**Comment by raine** [comment]
Thanks, I suppose we can close this!
