### ISSUE TITLE
If field is empty, display notification not error

### ISSUE THREAD

**Issue by yaoberh** [Language-Tools/anki-hyper-tts#19]
When reviewing and playing on the fly from a field which not always contains text, for example a Sentence field, one has to first close the dialogue showing that no text is present before being able to continue studying. Would be ideal to just have a notifiaction saying that there was no text in the specified field, or maybe just an option to disable notifications when this happens?
![image](https://user-images.githubusercontent.com/30667087/153030662-277528e5-c479-4ede-aa06-50be93a1b465.png)

**Comment by luc-languagetools** [comment]
Thank you for the suggestion, I agree a tooltip or notification would be less intrusive. Can you get in touch with me hypertts@airpost.net ? I want to increase your trial quota to give you more time to test.

**Comment by luc-languagetools** [comment]
This is now supported in HyperTTS 0.84 , see https://languagetools.anki.study/updates#2023-08-06
