### ISSUE TITLE
add ability to rename presets

### ISSUE THREAD

**Issue by luc-languagetools** [Language-Tools/anki-hyper-tts#21]
https://www.reddit.com/r/Anki/comments/sh2f7n/im_the_maintainer_of_awesometts_and_i_wrote_a_new/hwar3v4/?context=3

**Comment by SebastianEShelby** [comment]
no news on this?

**Comment by luc-languagetools** [comment]
done. https://languagetools.anki.study/updates#2023-10-18

**Comment by SebastianEShelby** [comment]
> done. https://languagetools.anki.study/updates#2023-10-18

Looks great. How do I generate multiple sounds for multiple words in the same field? I've been having trouble with this for a while now and I saw you mention somewhere it may be possible.

Here's what I mean:

In the "Back" field I want to have 3 words and 3 _separate_ sounds:
`
word1 sound1
word2 sound2
word3 sound3
`

Currently, the created sound reads all 3 words together in a single audio track
