### ISSUE TITLE
When editing a single card, Add audio UI shows presets that wouldn't work

### ISSUE THREAD

**Issue by jhhr** [Language-Tools/anki-hyper-tts#32]
Since pressing Add audio for a card causes an error if the preset is targeting fields that are for a different deck, the preset shouldn't be shown in the card editor UI.
![hypertts-card-editor](https://user-images.githubusercontent.com/11407217/154836931-5d28fff9-9298-41c6-8a0f-a5cd8d484854.png)

This would make editing a single card require less clicks when the preset the user wants is already selected (eg. they have 1 preset per deck).

**Comment by luc-languagetools** [comment]
Good suggestion, just trying to think of whether that could cause an issue in some cases. In Language Tools, I tried to add a lot of smart logic to map from a field/deck/note combination to a language, and that kind of backfired for example with subdecks, people had to define this mapping multiple times. so before adding constraints, I want to make sure I'm not going to lock people out of certain configurations
