### ISSUE TITLE
Feature to apply preset on adding note to deck through AnkiConnect

### ISSUE THREAD

**Issue by jhhr** [Language-Tools/anki-hyper-tts#33]
Now that HyperTTS defines presets on with the source and target field defined (deck-specific) this kind of feature should be possible.
For example the ajt-furigana addon has a setting that applies the user's configured furigana adding when a note gets added:
https://github.com/Ajatt-Tools/Furigana/blob/main/reading.py#L132

This would further reduce time spent adding generated audio for users that regularly add new notes to their decks.

**Comment by jhhr** [comment]
I recall Language Tools had this kind of feature but it only allowed one voice per field?

**Comment by luc-languagetools** [comment]
this is possible and in general we should aim for more automation, but the complexity lies in how to detect which preset to apply
- we could go by deck (but this creates potential problems for subdecks)
- or by note type (but i have a counter example, I use the same note type for Mandarin and Cantonese)
- or combination of deck and note type, but this becomes very rigid. Some people have elaborate subdecks and they'd have to re-create this rule for every subdeck.
- or maybe just popup and ask the user if they want to add audio ?

This is specifically the issue that cause problems for some language tools users, they had to define  their language mapping multiple times in some cases.

**Comment by luc-languagetools** [comment]
with the preset mapping rules feature, HyperTTS moves closer to being able to generate audio automatically: https://languagetools.anki.study/updates#2023-10-18 , please take a look and see it makes sense to you, the next steps will be allowing fully automatic generation.

**Comment by luc-vocab** [comment]
more automation features coming in the future.
