### ISSUE TITLE
hyper TTS bar in "add card" or "edit" mode [conflict with Language Tools]

### ISSUE THREAD

**Issue by bayareadoc** [Language-Tools/anki-hyper-tts#39]
HyperTTS button to add audio in "edit" mode does not appear while LanguageTools add-on is applied. Is there a conflict between the two programs that doesn't allow me to use HyperTTS in  add card/edit mode?
See screenshot of add card:

![image](https://user-images.githubusercontent.com/100099905/155407348-42ee7f02-4371-49e4-8a6e-961d8eca2dd5.png)

See screenshot of edit mode:
![image](https://user-images.githubusercontent.com/100099905/155408570-8d414187-6710-48c2-a397-0af3f24aa068.png)

Anki version 2.1.49 (dc80804a( Python 3.8.6 Qt 5.14.2 PyQt 5.14.2)

**Comment by luc-languagetools** [comment]
yes i'm aware of the issue, there's a weird conflict which I haven't yet resolved. temporarily you can disable Language Tools, and you'll see the HyperTTS controls.

**Comment by luc-languagetools** [comment]
asking for help from anki developers
https://forums.ankiweb.net/t/2-addons-conflicting-with-svelte-components-editortoolbar-toolbar-insertgroup/18019

**Comment by luc-languagetools** [comment]
i'm waiting for a fix from the developers of Anki, which will likely come in 2.1.50

**Comment by luc-languagetools** [comment]
should be fixed in versions which support 2.1.50.
