### ISSUE TITLE
Google Translate: Hebrew

### ISSUE THREAD

**Issue by nwwt** [Language-Tools/anki-hyper-tts#48]
Google Translate has recently added Hebrew to its TTS, seems it's not yet in your addon.

**Comment by luc-languagetools** [comment]
HyperTTS uses a library called gTTS (https://github.com/pndurette/gTTS) to enable Google Translate and it doesn't look like Hebrew support has been added yet, so we'll have to wait. For hebrew your best bet currently is Azure: https://languagetools.anki.study/voices/iw

**Comment by nwwt** [comment]
gTTS's most recent commit (23do) actually did add Hebrew.

**Comment by luc-languagetools** [comment]
Google Translate Hebrew was added to HyperTTS v0.48, please give it a try and please write a review if you're satisfied https://ankiweb.net/shared/info/111623432

**Comment by nwwt** [comment]
Done, thanks!
