### ISSUE TITLE
Repeated error after trying to remove rule

### ISSUE THREAD

**Issue by nwwt** [Language-Tools/anki-hyper-tts#55]
Trying to remove a (regex) text replacement rule yields the following error on repeat, requiring Anki to be killed:
```
Caught exception:
TypeError: invalid result from TextReplacementsTableModel.flags(), NoneType cannot be converted to QFlags<Qt::ItemFlag>
```

**Comment by luc-languagetools** [comment]
Hi, can you tell me which Anki version you're using ?

**Comment by nwwt** [comment]
sorry, it's Anki 2.1.50 (5dab7ed4)

**Comment by luc-languagetools** [comment]
many thanks, i'll try to reproduce this on 2.1.49. If you need absolute stability, I suggest you temporarily downgrade to 2.1.49.

**Comment by luc-languagetools** [comment]
I tried to add a workaround, please try HyperTTS v0.52

**Comment by nwwt** [comment]
Removal works fine now, no error anymore. Thanks!

**Comment by luc-languagetools** [comment]
Great! Note that the HyperTTS editor toolbar doesn't yet work on 2.1.50, I'm waiting for some help from the developers of Anki in order to fix that. Besides that, I expect HyperTTS should work with 2.1.50.
