### ISSUE TITLE
Beginning of generated audio seems to be cut off in certain cases

### ISSUE THREAD

**Issue by telotortium** [Language-Tools/anki-hyper-tts#61]
In certain cases, it seems that the audio generated by the Azure voices for zh-CN has the beginning slightly cut off. For example, when I try to generate audio for the phrase "他冻僵了。" (pinyin "Tā dòngjjāng le."), the beginning plosive on the "Ta" is cut off, so it sounds like "ā dòngjjāng  le.", which is confusing when reviewing audio cards. I generated the audio using the "Example 1 Azure" setting in my config (inserted below). Some of the voices in the config seem to have this problem, and some of them don't.

Config: https://pastebin.com/vMgs9vpQ

**Comment by luc-languagetools** [comment]
One thing you could try is to insert a short SSML pause at the the sound, use a regex replacement to replace ^ with <break time="250ms"/>and check whether that changes anything
<img width="961" alt="ssml_break" src="https://user-images.githubusercontent.com/4581915/163495512-dd45ceb7-3296-4988-bfa9-7c3d056bc67c.png">
.

**Comment by luc-languagetools** [comment]
@telotortium were you able to try this ?

**Comment by telotortium** [comment]
I tried it, but I can't reproduce. One of the voices in that preset just has less of a plosive sound, but it's not improved by adding a pause. I'll just regenerate the audio if I don't like how it's generated in the future (which is what I ended up doing).

**Comment by luc-languagetools** [comment]
OK. this seems to be 100% a result of the TTS service, so not something HyperTTS has control over.
