### ISSUE TITLE
Applying multiple presets at the same time

### ISSUE THREAD

**Issue by promisedlandt** [Language-Tools/anki-hyper-tts#63]
Hey, I have cards on which I want to add audio to two different fields, from two different source fields. For example:

full sentence: This is an example
sentence: This is an ___
missing word: example
full sentence audio: <generate from full sentence>
missing word audio: <generate from missing word>

Currently I have solved this by having two presets and applying them individually. 
I would prefer to have a "preset group" instead that I only have to apply once.

**Comment by luc-languagetools** [comment]
let's track #71  instead @promisedlandt 
i'll keep you updated
