### ISSUE TITLE
Enable auto-insert during note creation

### ISSUE THREAD

**Issue by promisedlandt** [Language-Tools/anki-hyper-tts#64]
Batch creation of audio is always fine when using a TTS service. 
However, with user generated content like Forvo, the quality varies a lot, up to a point of required manual intervention (either manually inserting a different Forvo pronounciation via anki-forvo-dl, or generating it via TTS).

With AwesomeTTS, the audio was auto-inserted while I was creating the note so I was always checking it. Now I either need to create the audio on the collection and manually check all cards, or I need use the hotkey to preview the audio on every card, which is annoying, especially combined with #63 (preview audio, change preset, preview audio again).

**Comment by promisedlandt** [comment]
I'm sorry, it was Language Tools that had the Live Updates feature, not AwesomeTTS. I guess once #39 is fixed in Anki I can use Language Tools with the live updates to add Forvo pronounciations, and if I don't like them I can manually run a HyperTTS preset.
Sorry for the confusion!

**Comment by luc-languagetools** [comment]
If all you're interested in is audio, then maybe the ideal solution would be to have something like live update in HyperTTS. Then you would hear the sound immediately and you could cherry pick the audio if you didn't like the one you got.

**Comment by luc-languagetools** [comment]
Yes that's going to be the difficulty: guessing which preset is appropriate for the given note. Though we could ask the user to confirm automated addition is desired, and if adding a long string of notes one after another (for same deck/same note type), they could keep this "auto add" switch on.

**Comment by promisedlandt** [comment]
Sure, selecting a preset and clicking a button to auto-add it sounds really good.
I'll just re-open this issue to track it then :)

**Comment by luc-vocab** [comment]
Please check the latest "preset mapping" feature. The next step after that will be full automation when the user types.

**Comment by promisedlandt** [comment]
Just tried it, very nice. I especially like the option to filter by just note type, or note type + deck.

What's not great for me is the error handling. I have a "root form" field for my cloze cards, which is filled on only about 30% of cards. That means on 70% of cards I'll get an error pop-up for something that is not an error.  
I've switched to "Tooltip" for now, but it's still somewhat annoying, and I'm afraid I'll miss actual errors if I switch to "Nothing".  
Would be great to have an option like "allow empty". 

Either way, great feature.
