### ISSUE TITLE
Status Code 500: Internal Server Error

### ISSUE THREAD

**Issue by carlos1172** [Language-Tools/anki-hyper-tts#68]
Hi, I get this error often. How do I fix it?

Encountered an error while Playing Realtime Audio: Could not request audio for [The blank nucleus is the portion of the medial longitudinal fasciculus responsible for vertical gaze]: status code 500: Internal Server Error (voice: English (US), Male, Guy (Neural), Azure)

**Comment by luc-languagetools** [comment]
closing as we are in contact over email to determine the issue.
