### ISSUE TITLE
Error Code 403 from Naver Papago

### ISSUE THREAD

**Issue by jebra102** [Language-Tools/anki-hyper-tts#78]
I keep getting an error trying to add TTS to cards. I'm trying to use naver papago and keep getting this problem.
![image](https://user-images.githubusercontent.com/117840763/200863583-3e5841d0-5fe9-4bb3-88af-e3c4d964533b.png)
Nothing about the settings was changed, I could use it less than 24h ago with zero problems.

**Comment by lowkeydying** [comment]
I just dowloaded this add-on for the sole purpose of using naver papago audio and am having the same issue.

**Comment by jebra102** [comment]
It works again for me. An update was issued, so I'll close this one.

**Comment by luc-languagetools** [comment]
correct, should be fixed in hypertts 0.70
