### ISSUE TITLE
error code 403 for naverpapago

### ISSUE THREAD

**Issue by lowkeydying** [Language-Tools/anki-hyper-tts#79]
<img width="817" alt="Screen Shot 2022-11-11 at 9 36 17 AM" src="https://user-images.githubusercontent.com/117873288/201235447-a4425629-85a2-4e8b-95c5-8b6b580b0604.png">

Hi unable to add audio from papago for the last two days. Installed the 11/10 update, but nothing has changed. Still getting the notification that a login is required.

**Comment by luc-languagetools** [comment]
which hypertts version are you on now ?

**Comment by lowkeydying** [comment]
the .70 version, I'm going to reinstall anki and see if that fixes it.

**Comment by lowkeydying** [comment]
we can all blame Anki, or at least I will, fixed!

**Comment by luc-languagetools** [comment]
I suspect you needed a restart after installing the HyperTTS update.
