### ISSUE TITLE
Unknow error while Saving Preset

### ISSUE THREAD

**Issue by Casartellii** [Language-Tools/anki-hyper-tts#8]
![anki_L6o2M7zXX2](https://user-images.githubusercontent.com/88219689/151670259-cfe8da03-a68d-4b52-986f-df7b0c4996df.png)

**Comment by luc-languagetools** [comment]
do you have more details on what actions led to this result ?

**Comment by Casartellii** [comment]
It seems to be a problem with the option "Single: a single voice will be used for all notes".


![anki_MOe2DWMZHl](https://user-images.githubusercontent.com/88219689/151683558-5e0b3452-b4f6-4001-aad5-9f04d651cefe.gif)

**Comment by luc-languagetools** [comment]
I see, thank you for the video, I can see you have the filters configured in a way that no voice can possibly match. Let me add some safeguards around that.

**Comment by luc-languagetools** [comment]
In v0.17 there is now a clear error message.
