### ISSUE TITLE
is it possible to use espeak backend by piping text instead of creating many audio files?

### ISSUE THREAD

**Issue by sudomain** [Language-Tools/anki-hyper-tts#81]
Hi I'm looking to use the espeak back end for most of my existing cards. It would be overkill to both generate and keep an audio file for each of them (~53,000 cards at the moment). Would it be possible to pipe the text that needs to be spoken into espeak? It has a `--stdin ` option to accept the input.

**Comment by luc-languagetools** [comment]
Why don't you use realtime TTS ? That way the audio will be generated only when you review.

**Comment by sudomain** [comment]
Sorry, I'm not sure what you mean by "realtime TTS". Is it a back end for hypertts? A different add-on?

**Comment by luc-languagetools** [comment]
https://languagetools.anki.study/tutorials/hypertts-realtime-audio

**Comment by sudomain** [comment]
That seems to work great. Sorry I didn't know about that setting or the website. Is there a way to set the locale of the espeak service across the whole add-on? I have a lot of templates to enable realtime tts for. Alot of the work I'd need to do is switching the espeak language from the alphabetically first (Afrikaans) to English (US) for each of my fields.

Also would you accept a PR that adds another service to HyperTTS? I haven't made it (and may not have the skills to), but I want to use the Android tts service on my phone. Let me explain: I run Anki (desktop) on my non-rooted phone in a Linux PRoot environment in Termux. Termux has a tts tool called `termux-tts-speak` which is basically a bridge to the Android tts service (or others if they're installed). I don't know many people that run Anki this way, so I understand if you don't want another service. I'd just rather not reinvent the wheel and make another Anki add-on for TTS especially when HyperTTS has so many services already.

**Comment by luc-languagetools** [comment]
How many different templates do you have ? As you know in HyperTTS, the source field, destination field, and voice selection are all part of the preset and this is a significant difference compared to AwesomeTTS. 

Adding a new service to HyperTTS is extremely easy. You'll have no difficulty if you know at least a little bit of python. I specifically designed HyperTTS to make it extremely easy to add services. just clone `service_espeakng.py` and implement your own service, put it in the services directory and you're done. I suspect the result will be much higher quality than espeak.

**Comment by sudomain** [comment]
A lot of templates. I try changing my local install of the add-on and try to set it to EN_US for espeak.

Would the new service need a file in [the `external` directory](https://github.com/Language-Tools/anki-hyper-tts/tree/main/external) to handle additional arguments?

**Comment by luc-languagetools** [comment]
no need to add anything in the external directory, just clone `service_espeakng.py`.

**Comment by sudomain** [comment]
Sorry for the late reply. I'm going to attempt the new service today and this weekend but I have a couple questions:

1. I don't think I can just clone `service_espeakng.py` as this file [calls an espeakng module](https://github.com/Language-Tools/anki-hyper-tts/blob/03ec7335e9bde7aab6de72320f7355036b5f94af/services/service_espeakng.py#L6), which [does the work via subprocess](https://github.com/Language-Tools/anki-hyper-tts/blob/main/external/espeakng/__init__.py). What's the purpose of separating these files?

2. The espeak service uses [temporary files](https://github.com/Language-Tools/anki-hyper-tts/blob/03ec7335e9bde7aab6de72320f7355036b5f94af/services/service_espeakng.py#L91). Rather than use this approach, can I pipe text to be read directly into `termux-tts-speak` using `Popen.communicate()`? More generally, why use temporary files at all if espeak-ng has an `--stdin` option?

I don't mean to critique your code and I'm very thankful for the add-on as an end user. I'm not really a developer and was just wondering about the temporary file approach so that I can learn. I apologize if any of this came off as rude.

**Comment by luc-languagetools** [comment]
1. easier maintenance
2. yes you can pipe, as long as you return the contents of the mp3 file in `get_tts_audio`
3. in `voice_list()`, you have to return an array of `voice.Voice` objects. you can just hardcode the gender to male.
4. How would a generic command line service work ? I suggest you do a termux-tts-speak specific service instead, it'll be simpler.

**Comment by sudomain** [comment]
Closing in favor of #96 as termux-tts-speak is probably better off as a speech-dispatcher output module since other programs rely on speechd
