### ISSUE TITLE
Feature Request: Ability to generate / preview audio  selection regardless of source/destination field.

### ISSUE THREAD

**Issue by Apocalypse612** [Language-Tools/anki-hyper-tts#83]
A simple shortcut for this would be nice, too.

Thanks!

**Comment by luc-languagetools** [comment]
How do you envision this to work ?

**Comment by Apocalypse612** [comment]
Select the words you want to be spoken via highlighting, issue the command (ideally via HotKey) which will use your currently selected audio preset (voice), and paste said sound file in the same location, replacing the highlighted word selection. Some might not want the word replaced, and instead placed before or after it, which could also be configurable.

**Comment by luc-languagetools** [comment]
With HyperTTS 1.00, the previous "generate for selection" feature has been removed, but I want to bring it back. Also requested by Dang Le over email.

**Comment by jbvoigt3** [comment]
I agree. Used to use it a lot. Jack"We are free to choose, but we are not free from the consequences of our choice."On Nov 12, 2023, at 14:13, Luc ***@***.***> wrote:﻿
With HyperTTS 1.00, the previous "generate for selection" feature has been removed, but I want to bring it back. Also requested by Dang Le over email.

**Comment by luc-languagetools** [comment]
also requested by Shelly over email

**Comment by luc-languagetools** [comment]
related: #146

**Comment by luc-languagetools** [comment]
also requested by Dennis over email

**Comment by luc-languagetools** [comment]
Generating audio based on selection has been added in HyperTTS 1.07, see https://languagetools.anki.study/updates#2024-01-31
