### ISSUE TITLE
real-time audio shouldn't generate an error message if a field is empty 

### ISSUE THREAD

**Issue by protomanexe123** [Language-Tools/anki-hyper-tts#89]
I've used HyperTTS and Language Tools regularly for the last year to add audio to my spanish deck.  

When I create my cards in Spanish I tend to have English on the Front with a Spanish Hint field to guide how I translate it to Spanish. I don't always need hints, however, so a lot of time that field is blank. 

Currently I can't make that field automatically add audio to it, since if the field is blank it generates an error message and stops everything.  IF it weren't for the error message I could use that feature on 2-3 out of every 5 or 6 cards that I generate and skip the steps where I have to add audio to that field.

**Comment by luc-languagetools** [comment]
Can you give me more details about the exact setup of the note, what's happening right now and what you'd like to see happen instead?

**Comment by protomanexe123** [comment]
So my Spanish Hints field is on the front of the card and I’ll set it to add real-time audio to just that field.  Unfortunately, anytime that field is blank (because I don’t know always need the hint) while doing my reviews I get an error message.  IT says: Encountered an error while playing realtime audio: source text is empty.



From: Luc ***@***.***>
Date: Saturday, January 21, 2023 at 6:18 PM
To: Language-Tools/anki-hyper-tts ***@***.***>
Cc: protomanexe123 ***@***.***>, Author ***@***.***>
Subject: Re: [Language-Tools/anki-hyper-tts] real-time audio shouldn't generate an error message if a field is empty (Issue #89)

Can you give me more details about the exact setup of the note, what's happening right now and what you'd like to see happen instead?

**Comment by luc-languagetools** [comment]
One thing which might be feasible is to change the alert message to a warning, like a tooltip at the bottom. It wouldn't interrupt your workflow.

**Comment by protomanexe123** [comment]
Yeah! That’d be cool.  The feature would save me a lot of time.

**Comment by khonkhortisan** [comment]
Here's a hack to remove the error, and display a tooltip. https://github.com/Language-Tools/anki-hyper-tts/issues/19
%Appdata%\Anki2\addons21\111623432\hypertts.py lines 19, 108, 115, 276, 295
```diff
diff --git a/hypertts.py b/hypertts.py
index 1452190..7dfde24 100644
--- a/hypertts.py
+++ b/hypertts.py
@@ -16,6 +16,7 @@ import aqt.progress
 import aqt.addcards
 import anki.notes
 import anki.cards
+from aqt.utils import tooltip
 
 constants = __import__('constants', globals(), locals(), [], sys._addon_import_level_base)
 options = __import__('options', globals(), locals(), [], sys._addon_import_level_base)
@@ -104,14 +105,14 @@ class HyperTTS():
         source_text = self.get_source_text(note, batch.source, text_override)
         processed_text = text_utils.process_text(source_text, batch.text_processing)
         if len(processed_text) == 0:
-            raise errors.SourceTextEmpty()        
+            tooltip("HyperTTS: Source text is empty");return (None, processed_text)#raise errors.SourceTextEmpty()        
         return self.get_audio_file(processed_text, batch.voice_selection, audio_request_context)
 
     def get_realtime_audio(self, realtime_model: config_models.RealtimeConfigSide, text):
         source_text = text
         processed_text = text_utils.process_text(source_text, realtime_model.text_processing)
         if len(processed_text) == 0:
-            raise errors.SourceTextEmpty()
+            tooltip("HyperTTS: Source text is empty");return (None, processed_text)#raise errors.SourceTextEmpty()
         return self.get_audio_file(processed_text, realtime_model.voice_selection, context.AudioRequestContext(constants.AudioRequestReason.realtime))
 
     def get_audio_file(self, processed_text, voice_selection, audio_request_context):
@@ -272,7 +273,7 @@ class HyperTTS():
         processed_text = text_utils.process_text(source_text, batch_text_processing)
         # logger.info(f'before text processing: [{source_text}], after text processing: [{processed_text}]')
         if len(processed_text) == 0:
-            raise errors.SourceTextEmpty()
+            tooltip("HyperTTS: Source text is empty");return (None, processed_text)#raise errors.SourceTextEmpty()
         return processed_text
 
     # sound generation
@@ -291,7 +292,7 @@ class HyperTTS():
     def play_sound(self, source_text, voice, options):
         logger.info(f'playing audio for {source_text}')
         if source_text == None or len(source_text) == 0:
-            raise errors.SourceTextEmpty()        
+            tooltip("HyperTTS: Source text is empty");return (None, source_text)#raise errors.SourceTextEmpty()        
         full_filename, audio_filename = self.generate_audio_write_file(source_text, voice, options, context.AudioRequestContext(constants.AudioRequestReason.preview))
         self.anki_utils.play_sound(full_filename)
 
```
*If you have another addon that shows tooltips (Review Hotmouse, Color Confirmation) it'll replace this tooltip

**Comment by luc-languagetools** [comment]
same issue as #114
also requested by Eugen over email

**Comment by luc-languagetools** [comment]
This is now supported in HyperTTS 0.84 , see https://languagetools.anki.study/updates#2023-08-06

**Comment by protomanexe123** [comment]
Awesome! I’ve wanted a fix for this forever.

From: Luc ***@***.***>
Date: Sunday, August 6, 2023 at 7:37 AM
To: Language-Tools/anki-hyper-tts ***@***.***>
Cc: protomanexe123 ***@***.***>, Author ***@***.***>
Subject: Re: [Language-Tools/anki-hyper-tts] real-time audio shouldn't generate an error message if a field is empty (Issue #89)

This is now supported in HyperTTS 0.84 , see https://languagetools.anki.study/updates#2023-08-06

**Comment by luc-languagetools** [comment]
I had to roll back the release temporarily due to an issue but will be rolling it out again later.

**Comment by luc-languagetools** [comment]
I've re-enabled this in HyperTTS 0.86
