### ISSUE TITLE
LIttle trick i used to add sound to my multi-language field

### ISSUE THREAD

**Issue by ganqqwerty** [Language-Tools/anki-hyper-tts#91]
I wanted to have the sound files for the Tatoeba examples. They typically look like that: 

``` 
学校はどう？
How's school?

学校は好き？
Do you like school?

学校だよ。
I'm at school. 
```

See the problem? If I simply use the Japanese voice, it will also try to pronounce the English stuff with cute Japanese accent. So I [went to stackoverflow](https://stackoverflow.com/questions/46680106/regex-notepad-delete-all-except-japanese-character-words) and found a regular expression that allows to remove all non-Japanese characters: 

``` [^、-〿぀-ゟ゠-ヿ＀-￯一-龯\r\n]+(?![、-〿぀-ゟ゠-ヿ＀-￯一-龯\d])|[…“”’\"'–] ```

I went to text-replacement and added a regex rule, so it removed all english stuff!  I used `" "` as replacement.

![CleanShot 2023-01-29 at 01 46 43@2x](https://user-images.githubusercontent.com/697308/215297846-84f72539-92f2-46ef-8836-da882016f9d2.png)

**Comment by luc-languagetools** [comment]
Great thank you for sharing ! But just curious, why don't you use different fields for the english and japanese ? that's how most people do it.

**Comment by luc-languagetools** [comment]
understood. thanks for sharing the tip. Closing this for now, let me know if you need more help !
