### ISSUE TITLE
I'm not even seeing a HyperTTS dropdown when I install this 

### ISSUE THREAD

**Issue by pandichef** [Language-Tools/anki-hyper-tts#92]
Anki version for Windows 10:
Version ⁨2.1.53 (96bacf79)⁩
Python 3.9.7 Qt 6.3.0 PyQt 6.3.0

**Comment by luc-languagetools** [comment]
do you see services configuration after restarting Anki ? https://languagetools.anki.study/tutorials/hypertts-getting-started

**Comment by pandichef** [comment]
yes, and I see hyperTTS in tools dropdown menu

**Comment by luc-languagetools** [comment]
ok then you can follow the tutorial and let me know if you get stuck.

**Comment by pandichef** [comment]
So I click "Collection Audio" and it tells me to go to "HyperTTS -> Add Audio (Collection)...".
But this menu doesn't exist.

**Comment by luc-languagetools** [comment]
Are you in the note browser ? Feel free to show a screenshot.

**Comment by pandichef** [comment]
![Capture](https://user-images.githubusercontent.com/17748513/217144964-a83c0512-414a-456c-a14f-ece7c3b7be57.PNG)

**Comment by luc-languagetools** [comment]
Do you know how to go to the Anki card browser ? click the browse button at the top.

**Comment by pandichef** [comment]
got it.  I'm very new to Anki.  Thanks for your patience.
