### ISSUE TITLE
[ERROR] On the fly tts generation returns error

### ISSUE THREAD

**Issue by caasion** [Language-Tools/anki-hyper-tts#95]
When I try to use the on-the-fly format for hyperTTS, it gives me an error `Realtime Preset not found: realtime_0`. This has been quite frustrating because I don't understand the error message.

**Comment by luc-languagetools** [comment]
please remove the realtime audio tag and re-add it, do you know how to ?

**Comment by caasion** [comment]
HI!

sorry for the delayed reply, but I am not sure how to do on-the-fly tts in general. I managed to fix this error by changing `es_ES` to `en_EN` but the tts still doesn't seem to be working. (it says no player found for TTSTag.

I wish to generate on-the-fly for Korean and Spanish. Could you guide me or give me a general template of how to do on-the-fly TTS?

**Comment by luc-languagetools** [comment]
Please follow the tutorial here https://languagetools.anki.study/tutorials/hypertts-getting-started and let me know where you get stuck.

**Comment by caasion** [comment]
Thank you! the tutorial you've sent is very detailed and the website looks good too!
