### ISSUE TITLE
Integration with speech-dispatcher?

### ISSUE THREAD

**Issue by sudomain** [Language-Tools/anki-hyper-tts#96]
Would it be possible to have HyperTTS inferface with [speech-dispatcher](https://github.com/brailcom/speechd) for *nix computers? Some of the benefits according to `info speech-dispatcher `:

Speech Dispatcher from user's point of view:

   * ability to freely combine applications with your favorite
     synthesizer
   * message synchronization and coordination
   * less time devoted to configuration of applications

   Speech Dispatcher from application programmers's point of view:

   * easy way to make your applications speak
   * common interface to different synthesizers
   * higher level synchronization of messages (priorities)
   * no need to take care about configuration of voice(s)

**Comment by luc-languagetools** [comment]
do you have speech-dispatcher working on your computer ?

**Comment by sudomain** [comment]
yes, though it somewhat depends on how you define "computer" lol. Without going into too much detail I have a Debian PRoot environment running in Termux running on an Android physical device. I use an app to connect to a VNC server on the local device and run the latest Anki which was installed with pip.

speechd has output modules that would allow new outputs for HyperTTS, such as SpeakUp and Festival. It also has a [Python API](https://github.com/brailcom/speechd/tree/master/src/api/python).

**Comment by luc-languagetools** [comment]
OK, are you interested in taking a shot at implementing the speech-dispatcher service ? One of the objectives when I wrote HyperTTS was to make it trivial to add services. You could clone the espeakng service for example.

**Comment by sudomain** [comment]
I will if I have to 😄

**Comment by sudomain** [comment]
Off-topic, but are you aware of this?
https://doc.qt.io/qt-5/qtspeech-index.html

**Comment by luc-languagetools** [comment]
Just curious, did you look at how HyperTTS services are created ? It's really, really easy.
