### ISSUE TITLE
Feature Request: Abilty to filter out <img src="*.jpg"> in Audio Collection

### ISSUE THREAD

**Issue by cafelinked** [Language-Tools/anki-hyper-tts#98]
In real-time audio, file name of the images are not generated which is good. However, in audio collection, the file name is being generated. I have tried the following RegEx rule, but it does not seem to filter it out. 

`<img src=".*?\.jpg">`
`".*?\.jpg"`
`".*?\.jpg$"`

The following should be filtered out: jpg, jpeg, TIFF, png, bmp. Using Asterisk that represents any file name regardless of their length. 

Example: https://voca.ro/1jhpFP4EF5xn

**Comment by luc-languagetools** [comment]
Looks like you found a solution by yourself, which is good, but why do you mix image filenames with text when generating audio ? the cleanest approach would be to separate them in different fields.

**Comment by cafelinked** [comment]
> Looks like you found a solution by yourself, which is good, but why do you mix image filenames with text when generating audio ? the cleanest approach would be to separate them in different fields.

I agree. Hence I've decided to re-arrange all my decks to have images completely in separate fields.
